import { Inter } from 'next/font/google'
import './globals.css'
import HeaderTop from '@/components/HeaderTop'
import HeaderMain from '@/components/HeaderMain'
import Navbar from '@/components/Navbar'
import MobNavbar from '@/components/MobNavbar'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <HeaderTop />
        <HeaderMain />
        <Navbar />
        <MobNavbar /> 
        {children}
        <Footer />
      </body>
    </html>
  )
}
